# Generated by Django 4.1 on 2022-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_Name", models.CharField(max_length=200)),
                ("Last_Name", models.CharField(max_length=200)),
                ("Email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
